version: "3.9"
services:
    backend:
        container_name: backend
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 9229:9229
        depends_on:
            - database
        volumes:
            - ./:/app
        networks:
            - master
    database:
        image: mongo
        container_name: mongodb
        restart: always
        volumes:
            - ./database:/data/db
        ports:
            - 27017:27017
        command: mongod --noauth
        networks:
            - master
networks:
    master:
        driver: bridge
